In [2]:
import torch

x = torch.rand(3, 3)
print("Random tensor:")
print(x)


Random tensor:
tensor([[0.1937, 0.4033, 0.3204],
        [0.5183, 0.0411, 0.0496],
        [0.6787, 0.8627, 0.0955]])


In [3]:
if torch.cuda.is_available():
  print("gpu is avilaible")
else:
  print("gpu is not avilaible ")

gpu is not avilaible 


In [4]:
import torch
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")


GPU available: False
Running on CPU


## creating a tensor 


In [5]:
## using empty
a=torch.empty(2,3)
type(a)
torch.zeros(3,3)
torch.ones(3,3)
torch.rand(4,5)

tensor([[0.4576, 0.6093, 0.0366, 0.8134, 0.0208],
        [0.6887, 0.8618, 0.1553, 0.8491, 0.7078],
        [0.9242, 0.5125, 0.7882, 0.6910, 0.9305],
        [0.5227, 0.0626, 0.2492, 0.2193, 0.4485]])

In [6]:
torch.tensor([[1,2,3,4],[7,8,9,6]])

tensor([[1, 2, 3, 4],
        [7, 8, 9, 6]])

## TENSOR SHAPE

In [9]:
a=torch.tensor([[1,2,3,4],[1,5,6,78]])
a.shape

torch.Size([2, 4])

In [14]:
## bahut baar kya hota hain hume same shape ka random tensor banana hota hain 
## use empty_like 
torch.empty_like(a)

tensor([[2440280015552,             0,             0,             0],
        [            0,             0,             0,             0]])

In [15]:
torch.zeros_like(a)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [24]:
torch.rand_like(a,dtype=torch.float32)

tensor([[0.1312, 0.3727, 0.5360, 0.3128],
        [0.1227, 0.6382, 0.0831, 0.7218]])

## TENSOR DATA TYPES dtype attribute 

In [18]:
# find data type 
x.dtype

torch.float32

In [22]:
## assign data types 
b=torch.tensor([1.2,2,3,3,5,4.5],dtype=torch.int32)

In [23]:
## we can convert data type using .to function
b.to(torch.float32)

tensor([1., 2., 3., 3., 5., 4.])

## MATHMATICAL OPERATION 
1=SCALER OPERATION 

In [26]:
a=torch.rand(2,3)
a

tensor([[0.2765, 0.2181, 0.8289],
        [0.6939, 0.2343, 0.2803]])

In [27]:
a+2

tensor([[2.2765, 2.2181, 2.8289],
        [2.6939, 2.2343, 2.2803]])

In [28]:
a*3

tensor([[0.8295, 0.6543, 2.4866],
        [2.0816, 0.7030, 0.8409]])

In [29]:
a-1

tensor([[-0.7235, -0.7819, -0.1711],
        [-0.3061, -0.7657, -0.7197]])

## element wise 


In [31]:
b=torch.rand(3,3)
c=torch.rand(3,3)
b,c

(tensor([[0.6547, 0.1514, 0.6511],
         [0.9136, 0.8157, 0.0328],
         [0.6880, 0.7593, 0.8245]]),
 tensor([[0.8396, 0.8450, 0.3076],
         [0.2837, 0.0088, 0.6094],
         [0.0701, 0.0685, 0.6291]]))

In [32]:
x=b+c
x

tensor([[1.4943, 0.9964, 0.9587],
        [1.1973, 0.8245, 0.6423],
        [0.7581, 0.8278, 1.4536]])

## inplace operation 


In [39]:
m=torch.rand(2,3)
m
n=torch.rand(2,3)
m,n

(tensor([[0.3597, 0.4448, 0.1431],
         [0.3635, 0.9141, 0.6037]]),
 tensor([[0.3149, 0.1205, 0.6158],
         [0.6630, 0.9266, 0.9939]]))

In [38]:
m.add_(n)

tensor([[1.7689, 1.0737, 0.8138],
        [0.8195, 0.9508, 1.4153]])

tensor([[0.3597, 0.4448, 0.1431],
        [0.3635, 0.9141, 0.6037]])

## copy a tensor  using clone function
