In [1]:
import torch

x = torch.rand(3, 3)
print("Random tensor:")
print(x)


Random tensor:
tensor([[0.8721, 0.6158, 0.8402],
        [0.2227, 0.9324, 0.7270],
        [0.1321, 0.1446, 0.3020]])


In [2]:
if torch.cuda.is_available():
  print("gpu is avilaible")
else:
  print("gpu is not avilaible ")

gpu is not avilaible 


In [3]:
import torch
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")


GPU available: False
Running on CPU


## creating a tensor 


In [9]:
## using empty
a=torch.empty(2,3)
type(a)
torch.zeros(3,3)
torch.ones(3,3)
torch.rand(4,5)

tensor([[0.9371, 0.9195, 0.6925, 0.5087, 0.6123],
        [0.1078, 0.5903, 0.7950, 0.0586, 0.9326],
        [0.1397, 0.7169, 0.0506, 0.0376, 0.1171],
        [0.7824, 0.9610, 0.9383, 0.2543, 0.1202]])

In [10]:
torch.tensor([[1,2,3,4],[7,8,9,6]])

tensor([[1, 2, 3, 4],
        [7, 8, 9, 6]])

## TENSOR SHAPE