In [41]:
import torch

x = torch.rand(3, 3)
print("Random tensor:")
print(x)


Random tensor:
tensor([[0.2726, 0.3870, 0.8534],
        [0.1465, 0.9033, 0.8713],
        [0.4791, 0.1052, 0.1384]])


In [42]:
if torch.cuda.is_available():
  print("gpu is avilaible")
else:
  print("gpu is not avilaible ")

gpu is not avilaible 


In [43]:
import torch
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")


GPU available: False
Running on CPU


## creating a tensor 


In [44]:
## using empty
a=torch.empty(2,3)
type(a)
torch.zeros(3,3)
torch.ones(3,3)
torch.rand(4,5)

tensor([[0.2626, 0.1024, 0.9968, 0.1206, 0.9850],
        [0.2487, 0.1510, 0.6004, 0.1417, 0.9305],
        [0.8646, 0.8061, 0.9310, 0.8606, 0.8959],
        [0.6036, 0.1837, 0.6736, 0.4898, 0.2362]])

In [45]:
torch.tensor([[1,2,3,4],[7,8,9,6]])

tensor([[1, 2, 3, 4],
        [7, 8, 9, 6]])

## TENSOR SHAPE

In [46]:
a=torch.tensor([[1,2,3,4],[1,5,6,78]])
a.shape

torch.Size([2, 4])

In [47]:
## bahut baar kya hota hain hume same shape ka random tensor banana hota hain 
## use empty_like 
torch.empty_like(a)

tensor([[2440280015936,             0,             0,             0],
        [            0,             0,             0,             0]])

In [48]:
torch.zeros_like(a)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [49]:
torch.rand_like(a,dtype=torch.float32)

tensor([[0.0126, 0.6210, 0.6065, 0.8396],
        [0.7683, 0.8937, 0.1471, 0.3682]])

## TENSOR DATA TYPES dtype attribute 

In [50]:
# find data type 
x.dtype

torch.float32

In [51]:
## assign data types 
b=torch.tensor([1.2,2,3,3,5,4.5],dtype=torch.int32)

In [52]:
## we can convert data type using .to function
b.to(torch.float32)

tensor([1., 2., 3., 3., 5., 4.])

## MATHMATICAL OPERATION 
1=SCALER OPERATION 

In [53]:
a=torch.rand(2,3)
a

tensor([[0.9338, 0.0908, 0.5773],
        [0.1452, 0.8346, 0.3459]])

In [54]:
a+2

tensor([[2.9338, 2.0908, 2.5773],
        [2.1452, 2.8346, 2.3459]])

In [55]:
a*3

tensor([[2.8015, 0.2725, 1.7319],
        [0.4357, 2.5037, 1.0377]])

In [56]:
a-1

tensor([[-0.0662, -0.9092, -0.4227],
        [-0.8548, -0.1654, -0.6541]])

## element wise 


In [57]:
b=torch.rand(3,3)
c=torch.rand(3,3)
b,c

(tensor([[0.6556, 0.6456, 0.4692],
         [0.7526, 0.4027, 0.9243],
         [0.6889, 0.8711, 0.3602]]),
 tensor([[0.3240, 0.4824, 0.8824],
         [0.6792, 0.1356, 0.7174],
         [0.3297, 0.3031, 0.9629]]))

In [58]:
x=b+c
x

tensor([[0.9796, 1.1279, 1.3517],
        [1.4318, 0.5384, 1.6417],
        [1.0186, 1.1741, 1.3231]])

## inplace operation 


In [59]:
m=torch.rand(2,3)
m
n=torch.rand(2,3)
m,n

(tensor([[0.8935, 0.6403, 0.3156],
         [0.1427, 0.0706, 0.3235]]),
 tensor([[0.0952, 0.6316, 0.2616],
         [0.0235, 0.7473, 0.0452]]))

In [60]:
m.add_(n)

tensor([[0.9887, 1.2719, 0.5772],
        [0.1663, 0.8179, 0.3687]])

## copy a tensor  using clone function


In [62]:
## reshaping tensor 
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [63]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [66]:
## flatten single dimension main saare cheej lekar aata huu 
a.flatten()


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
b=torch.rand(2,3,4)
b

tensor([[[0.2631, 0.1323, 0.3454, 0.0726],
         [0.3278, 0.9803, 0.1298, 0.6826],
         [0.8441, 0.4189, 0.0335, 0.2548]],

        [[0.3807, 0.2818, 0.1313, 0.0733],
         [0.3543, 0.0660, 0.2531, 0.7956],
         [0.7987, 0.7546, 0.0064, 0.2678]]])

permute se aap koi bhi index change kar sakte ho 
like 0 par  2 1 par 3 2 par 4 


In [69]:
b.permute(2,0,1)

tensor([[[0.2631, 0.3278, 0.8441],
         [0.3807, 0.3543, 0.7987]],

        [[0.1323, 0.9803, 0.4189],
         [0.2818, 0.0660, 0.7546]],

        [[0.3454, 0.1298, 0.0335],
         [0.1313, 0.2531, 0.0064]],

        [[0.0726, 0.6826, 0.2548],
         [0.0733, 0.7956, 0.2678]]])

## UNSQUEEZ AND SQUEEZ


In [71]:
b=torch.rand(226,226,3)
## if you want to add a new dimension then we use unsqueez with its index kaha par 
b.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

## numpy and pytorch 

In [72]:
b=torch.tensor([1,2,3,4])
a=b.numpy()

In [75]:
a

array([1, 2, 3, 4], dtype=int64)