In [20]:
import torch
import torch.nn as nn


In [21]:
class models(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU,
      nn.Linear(3,1),
      nn.Sigmoid
    )
  def forward(self,features):
    out=self.network(features)
    return out 

In [22]:
 # ---------- Forward ----------
    ##y_pred = model(X_train_tensor)

    # ---------- Loss ----------
    ##loss = loss_function(y_pred, y_train_tensor)

    # ---------- Backward ----------
    ##optmizers.zero_grad()
    ##loss.backward()

    # ---------- Update ----------
    ##optmizers.step()

    # ---------- Print ----------
    ##if (epoch+1) % 10 == 0:
        ##print(f"Epoch {epoch+1}/{epochs} - Loss: {loss.item():.4f}")


## problem here is that we send all our data in forward propogation at oncre and then update weight s properly 

In [23]:
import torch 
from sklearn.datasets import make_classification


In [24]:
X,y=make_classification(
  n_samples=10,
  n_features=2,
  n_informative=2,
  n_redundant=0,
  n_classes=2,
  random_state=42
)

In [25]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [26]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [35]:
print(type(X))

<class 'torch.Tensor'>


In [36]:
print(type(y))

<class 'torch.Tensor'>


as we know in pytorch we have to given our x trai data into float 32 and y train daya in int 64 

In [29]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [30]:
from torch.utils.data import Dataset,DataLoader

In [37]:
class custom_datasets(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels
  def __len__(self):
    return self.features.shape[0]## no of rows in our dataset 
  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [38]:
dataset=custom_datasets(X,y)


In [39]:
len(dataset)

10

In [40]:
## if you want to access any index rows you can do 
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [41]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [42]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)

tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
tensor([[-1.1402, -0.8388],
        [ 1.0683, -0.9701]])
tensor([0, 1])
tensor([[ 1.7273, -1.1858],
        [-2.8954,  1.9769]])
tensor([1, 0])
tensor([[-0.7206, -0.9606],
        [ 1.7774,  1.5116]])
tensor([0, 1])
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])


if you want to data transformation ou can do it inside get item in datset class 