In [1]:
import torch 
import torch.nn as nn 


In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.Linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):## this forward function perfrom wx+b 
    out=self.Linear(features)
    out=self.sigmoid(out)
    return out 


In [4]:
## create a dataset 
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.5976],
        [0.5582],
        [0.5797],
        [0.6542],
        [0.5992],
        [0.5980],
        [0.5891],
        [0.5489],
        [0.6561],
        [0.6166]], grad_fn=<SigmoidBackward0>)

In [7]:
## now here you can also see your weight value and bias valuue that are used 
model.Linear.weight

Parameter containing:
tensor([[ 0.3893, -0.1088,  0.3010,  0.0908, -0.0476]], requires_grad=True)

In [13]:
model.Linear.bias

Parameter containing:
tensor([0.1316], requires_grad=True)

In [21]:
## now lets make a simple neuron network with 5 input features one hidden layer 3 neuron and one output neuron 
class models(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out 
    

In [22]:
features=torch.rand(10,5)
model=models(features.shape[1])
model(features)

tensor([[0.4647],
        [0.4300],
        [0.4758],
        [0.4747],
        [0.4781],
        [0.4816],
        [0.4371],
        [0.4810],
        [0.4942],
        [0.4699]], grad_fn=<SigmoidBackward0>)

In [26]:
model.linear1.weight

Parameter containing:
tensor([[-0.3371,  0.2304, -0.3951, -0.2417, -0.2456],
        [ 0.4035,  0.2610, -0.3339, -0.4106, -0.1822],
        [ 0.4111,  0.3735,  0.1997,  0.2917, -0.2657]], requires_grad=True)

In [ ]:
## def forward(self,features):
    #out=self.linear1(features)
    #out=self.relu(out)
    #out=self.linear2(out)
    #out=self.sigmoid(out)
    #return out we can potmize this code using container  

## now lets make this using sequential 

In [31]:
class Models(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.sequential=nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )
  def forward(self,features):
    out=self.sequential(features)
    return out


In [32]:
features=torch.rand(10,5)
model=Models(5)
model(features)

tensor([[0.4357],
        [0.4198],
        [0.4276],
        [0.4296],
        [0.4031],
        [0.4488],
        [0.4416],
        [0.4277],
        [0.4385],
        [0.4203]], grad_fn=<SigmoidBackward0>)