In [1]:
import torch 
import torch.nn as nn 


In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.Linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):## this forward function perfrom wx+b 
    out=self.Linear(features)
    out=self.sigmoid(out)
    return out 


In [4]:
## create a dataset 
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.5976],
        [0.5582],
        [0.5797],
        [0.6542],
        [0.5992],
        [0.5980],
        [0.5891],
        [0.5489],
        [0.6561],
        [0.6166]], grad_fn=<SigmoidBackward0>)

In [7]:
## now here you can also see your weight value and bias valuue that are used 
model.Linear.weight

Parameter containing:
tensor([[ 0.3893, -0.1088,  0.3010,  0.0908, -0.0476]], requires_grad=True)

In [13]:
model.Linear.bias

Parameter containing:
tensor([0.1316], requires_grad=True)